version: '3.8'

services: 

  localstack:
    container_name: localstack
    image: localstack/localstack:latest
    hostname: localstack
    environment: 
      - AWS_DEFAULT_REGION=us-east-1
      - SERVICES=s3
    ports: 
      - '4566-4583:4566-4583'
    volumes: 
      - /localstack:/tmp/localstack
      - /var/run/docker.sock:/var/run/docker.sock
      - ./aws:/docker-entrypoint-initaws.d

volumes:
  localstack: {}
