version: '3.8'

services: 

  localstack:
    container_name: localstack
    image: localstack/localstack:latest
    hostname: localstack
    environment: 
      - AWS_DEFAULT_REGION=us-east-1
      - SERVICES=s3
    ports: 
      - '4566-4583:4566-4583'
    volumes: 
      - /localstack:/tmp/localstack
      - /var/run/docker.sock:/var/run/docker.sock
      - ./aws:/docker-entrypoint-initaws.d
    healthcheck:
      test: ["CMD", "awslocal", "s3api", "wait", "bucket-exists", "--bucket", "test-bucket"]
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 10s

  app:
    container_name: app
    build: .
    ports:
      - "8080:8080"
    depends_on:
      localstack:
        condition: service_healthy
    environment:
      - S3_BUCKET_NAME=test-bucket

volumes:
  localstack: {}
